### ISSUE TITLE
Plugin does not work with Python 3.7 (cannot import name 'cached_property' from 'functools')

### ISSUE THREAD

**Issue by zarembat** [snjypl/airflow-provider-grafana-loki#5]
Hi,

I'm using Apache Airflow 2.3.3 with Python 3.7 and I get the following error when using this provider:

_apache-airflow-airflow-worker-1      |   File "/home/airflow/.local/lib/python3.7/site-packages/grafana_loki_provider/log/loki_task_handler.py", line 2, in <module>
apache-airflow-airflow-worker-1      | ValueError: Cannot resolve 'grafana_loki_provider.log.loki_task_handler.LokiTaskHandler': **cannot import name 'cached_property' from 'functools' (/usr/local/lib/python3.7/functools.py)**
apache-airflow-airflow-worker-1      |     LOGGING_CLASS_PATH = configure_logging()
apache-airflow-airflow-worker-1      |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/logging_config.py", line 73, in configure_logging
apache-airflow-airflow-worker-1      |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/logging_config.py", line 68, in configure_logging
apache-airflow-airflow-worker-1      |     dictConfig(logging_config)
apache-airflow-airflow-worker-1      |   File "/usr/local/lib/python3.7/logging/config.py", line 800, in dictConfig
apache-airflow-airflow-worker-1      |   File "/usr/local/lib/python3.7/logging/config.py", line 571, in configure_

This is expected as 'cached_property' has been introduced in Python 3.8.

Do you plan to add support for older Python versions (3.7 in my case)?

BTW. Great work! Makes integration with Loki super easy :)

**Comment by snjypl** [comment]
@zarembat  i have fixed the issue with cached_property. please try the latest version.  let me know if you face any other issues with python 3.7.

**Comment by zarembat** [comment]
This error is fixed, thanks. I opened another issue for a different error.
